# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
  # Uncomment the following line to enable commitPrefixes
  # commitPrefixes:
  #   pills:
  #     pattern: "^(PILL-\\d+)-.*"
  #     replace: "$1: "
gui:
  theme:
    selectedLineBgColor:
      - "reverse"
  nerdFontsVersion: "3"
  border: "rounded"
disableStartupPopups: true
confirmOnQuit: true
