[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "48h"
[".oh-my-zsh/custom/plugins/fast-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "48h"
[".oh-my-zsh/custom/plugins/zsh-aliases-exa"]
    type = "archive"
    url = "https://github.com/DarrinTisdale/zsh-aliases-exa/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "48h"
[".oh-my-zsh/custom/plugins/zsh-better-npm-completion"]
    type = "archive"
    url = "https://github.com/lukechilds/zsh-better-npm-completion/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "48h"
[".oh-my-zsh/custom/plugins/zsh-vi-mode"]
    type = "archive"
    url = "https://github.com/jeffreytse/zsh-vi-mode/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "48h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "48h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "48h"
{{ if (eq .chezmoi.os "linux") }}
[".fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/master.tar.gz"
    refreshPeriod = "48h"
{{ end }}
[".nerd-fonts"]
    type = "git-repo"
    url = "https://github.com/ryanoasis/nerd-fonts"
    refreshPeriod = "168h"
    [".nerd-fonts".clone]
        args = ["--depth=1"]
