[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "48h"
{{ if (eq .chezmoi.os "linux") }}
[".fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/refs/heads/master.zip"
    refreshPeriod = "48h"
{{ end }}
[".nerd-fonts"]
    type = "git-repo"
    url = "https://github.com/ryanoasis/nerd-fonts"
    refreshPeriod = "168h"
    [".nerd-fonts".clone]
        args = ["--depth=1"]
