version: '3.2'
services:
  chezmoi-ubuntu:
    build:
      context: .
      dockerfile: .docker/ubuntu/Dockerfile
    image: helmer_dotfiles_ubuntu
    tty: true
    volumes:
      - ./:/root/.local/share/chezmoi
  chezmoi-fedora:
    build:
      context: .
      dockerfile: .docker/fedora/Dockerfile
    image: helmer_dotfiles_fedora
    tty: true
    volumes:
      - ./:/root/.local/share/chezmoi

  # TODO: Add Debian

